

/*

   generated by makejapi4f   DO NOT EDIT

      Tue Feb 25 17:52:36 2003
 

 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>

#include "japi_p.h"

char* 	__j_c2f(char *s,int len)
{
	while(--len >= (int)strlen(s))
	    s[len]=32;
	return(s);
}

char* __j_f2c(char* s, char** a, int len)
{
    (*a)=(char*)malloc(len+1);
    memcpy((*a),s,len);
    (*a)[len]='\0';
	while((*a)[--len]==32 && len >= 0)
            (*a)[len]='\0';
    return(*a);
}

char* __j_f2c_d(char* s, int len)
{
    s[--len]='\0';
	while(s[--len]==32 && len >= 0)
            s[len]='\0';
    return(s);
}



/* japi functions */
int   j_start__()
{
    int  retval;
    retval = japi_start(  );
    return( retval );
}

int   j_connect__(char* arg0, int arg1)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_connect( __j_f2c( arg0, &jstr0, arg1) );
    free( jstr0 );
    return( retval );
}

void  j_setport__(int* arg0)
{
    japi_setport( *arg0 );
}

void  j_setdebug__(int* arg0)
{
    japi_setdebug( *arg0 );
}

int   j_frame__(char* arg0, int arg1)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_frame( __j_f2c( arg0, &jstr0, arg1) );
    free( jstr0 );
    return( retval );
}

int   j_button__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_button( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_graphicbutton__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_graphicbutton( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_checkbox__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_checkbox( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_label__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_label( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_graphiclabel__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_graphiclabel( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_canvas__(int* arg0, int* arg1, int* arg2)
{
    int  retval;
    retval = japi_canvas( *arg0, *arg1, *arg2 );
    return( retval );
}

int   j_panel__(int* arg0)
{
    int  retval;
    retval = japi_panel( *arg0 );
    return( retval );
}

int   j_borderpanel__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_borderpanel( *arg0, *arg1 );
    return( retval );
}

int   j_radiogroup__(int* arg0)
{
    int  retval;
    retval = japi_radiogroup( *arg0 );
    return( retval );
}

int   j_radiobutton__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_radiobutton( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_list__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_list( *arg0, *arg1 );
    return( retval );
}

int   j_choice__(int* arg0)
{
    int  retval;
    retval = japi_choice( *arg0 );
    return( retval );
}

int   j_dialog__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_dialog( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_window__(int* arg0)
{
    int  retval;
    retval = japi_window( *arg0 );
    return( retval );
}

int   j_popupmenu__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_popupmenu( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_scrollpane__(int* arg0)
{
    int  retval;
    retval = japi_scrollpane( *arg0 );
    return( retval );
}

int   j_hscrollbar__(int* arg0)
{
    int  retval;
    retval = japi_hscrollbar( *arg0 );
    return( retval );
}

int   j_vscrollbar__(int* arg0)
{
    int  retval;
    retval = japi_vscrollbar( *arg0 );
    return( retval );
}

int   j_line__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    int  retval;
    retval = japi_line( *arg0, *arg1, *arg2, *arg3 );
    return( retval );
}

int   j_printer__(int* arg0)
{
    int  retval;
    retval = japi_printer( *arg0 );
    return( retval );
}

int   j_image__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_image( *arg0, *arg1 );
    return( retval );
}

void j_filedialog__(int* arg0, char* arg1, char* arg2, char* arg3, int arg4, int arg5, int arg6)
{
    char* jstr0 = NULL;
    char* jstr1 = NULL;
    char* jstr2 = NULL;
    japi_filedialog( *arg0, __j_f2c( arg1, &jstr0, arg4), __j_f2c( arg2, &jstr1, arg5), __j_f2c_d( arg3, arg6) );
    __j_c2f(arg3, arg6);
    free( jstr0 );
    free( jstr1 );
    free( jstr2 );
}

void j_fileselect__(int* arg0, char* arg1, char* arg2, char* arg3, int arg4, int arg5, int arg6)
{
    char* jstr0 = NULL;
    char* jstr1 = NULL;
    char* jstr2 = NULL;
    japi_fileselect( *arg0, __j_f2c( arg1, &jstr0, arg4), __j_f2c( arg2, &jstr1, arg5), __j_f2c_d( arg3, arg6) );
    __j_c2f(arg3, arg6);
    free( jstr0 );
    free( jstr1 );
    free( jstr2 );
}

int   j_messagebox__(int* arg0, char* arg1, char* arg2, int arg3, int arg4)
{
    char* jstr0 = NULL;
    char* jstr1 = NULL;
    int  retval;
    retval = japi_messagebox( *arg0, __j_f2c( arg1, &jstr0, arg3), __j_f2c( arg2, &jstr1, arg4) );
    free( jstr0 );
    free( jstr1 );
    return( retval );
}

int   j_alertbox__(int* arg0, char* arg1, char* arg2, char* arg3, int arg4, int arg5, int arg6)
{
    char* jstr0 = NULL;
    char* jstr1 = NULL;
    char* jstr2 = NULL;
    int  retval;
    retval = japi_alertbox( *arg0, __j_f2c( arg1, &jstr0, arg4), __j_f2c( arg2, &jstr1, arg5), __j_f2c( arg3, &jstr2, arg6) );
    free( jstr0 );
    free( jstr1 );
    free( jstr2 );
    return( retval );
}

int   j_choicebox2__(int* arg0, char* arg1, char* arg2, char* arg3, char* arg4, int arg5, int arg6, int arg7, int arg8)
{
    char* jstr0 = NULL;
    char* jstr1 = NULL;
    char* jstr2 = NULL;
    char* jstr3 = NULL;
    int  retval;
    retval = japi_choicebox2( *arg0, __j_f2c( arg1, &jstr0, arg5), __j_f2c( arg2, &jstr1, arg6), __j_f2c( arg3, &jstr2, arg7), __j_f2c( arg4, &jstr3, arg8) );
    free( jstr0 );
    free( jstr1 );
    free( jstr2 );
    free( jstr3 );
    return( retval );
}

int   j_choicebox3__(int* arg0, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, int arg6, int arg7, int arg8, int arg9, int arg10)
{
    char* jstr0 = NULL;
    char* jstr1 = NULL;
    char* jstr2 = NULL;
    char* jstr3 = NULL;
    char* jstr4 = NULL;
    int  retval;
    retval = japi_choicebox3( *arg0, __j_f2c( arg1, &jstr0, arg6), __j_f2c( arg2, &jstr1, arg7), __j_f2c( arg3, &jstr2, arg8), __j_f2c( arg4, &jstr3, arg9), __j_f2c( arg5, &jstr4, arg10) );
    free( jstr0 );
    free( jstr1 );
    free( jstr2 );
    free( jstr3 );
    free( jstr4 );
    return( retval );
}

int   j_progressbar__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_progressbar( *arg0, *arg1 );
    return( retval );
}

int   j_led__(int* arg0, int* arg1, int* arg2)
{
    int  retval;
    retval = japi_led( *arg0, *arg1, *arg2 );
    return( retval );
}

int   j_sevensegment__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_sevensegment( *arg0, *arg1 );
    return( retval );
}

int   j_meter__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_meter( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

void  j_additem__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    japi_additem( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
}

int   j_textfield__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_textfield( *arg0, *arg1 );
    return( retval );
}

int   j_textarea__(int* arg0, int* arg1, int* arg2)
{
    int  retval;
    retval = japi_textarea( *arg0, *arg1, *arg2 );
    return( retval );
}

int   j_menubar__(int* arg0)
{
    int  retval;
    retval = japi_menubar( *arg0 );
    return( retval );
}

int   j_menu__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_menu( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_helpmenu__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_helpmenu( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_menuitem__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_menuitem( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_checkmenuitem__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_checkmenuitem( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

void  j_pack__(int* arg0)
{
    japi_pack( *arg0 );
}

void  j_print__(int* arg0)
{
    japi_print( *arg0 );
}

void  j_playsoundfile__(char* arg0, int arg1)
{
    char* jstr0 = NULL;
    japi_playsoundfile( __j_f2c( arg0, &jstr0, arg1) );
    free( jstr0 );
}

void  j_play__(int* arg0)
{
    japi_play( *arg0 );
}

int   j_sound__(char* arg0, int arg1)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_sound( __j_f2c( arg0, &jstr0, arg1) );
    free( jstr0 );
    return( retval );
}

void  j_setfont__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_setfont( *arg0, *arg1, *arg2, *arg3 );
}

void  j_setfontname__(int* arg0, int* arg1)
{
    japi_setfontname( *arg0, *arg1 );
}

void  j_setfontsize__(int* arg0, int* arg1)
{
    japi_setfontsize( *arg0, *arg1 );
}

void  j_setfontstyle__(int* arg0, int* arg1)
{
    japi_setfontstyle( *arg0, *arg1 );
}

void  j_seperator__(int* arg0)
{
    japi_seperator( *arg0 );
}

void  j_disable__(int* arg0)
{
    japi_disable( *arg0 );
}

void  j_enable__(int* arg0)
{
    japi_enable( *arg0 );
}

int   j_getstate__(int* arg0)
{
    int  retval;
    retval = japi_getstate( *arg0 );
    return( retval );
}

int   j_getrows__(int* arg0)
{
    int  retval;
    retval = japi_getrows( *arg0 );
    return( retval );
}

int   j_getcolumns__(int* arg0)
{
    int  retval;
    retval = japi_getcolumns( *arg0 );
    return( retval );
}

int   j_getselect__(int* arg0)
{
    int  retval;
    retval = japi_getselect( *arg0 );
    return( retval );
}

int   j_isselect__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_isselect( *arg0, *arg1 );
    return( retval );
}

int   j_isvisible__(int* arg0)
{
    int  retval;
    retval = japi_isvisible( *arg0 );
    return( retval );
}

int   j_isparent__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_isparent( *arg0, *arg1 );
    return( retval );
}

int   j_isresizable__(int* arg0)
{
    int  retval;
    retval = japi_isresizable( *arg0 );
    return( retval );
}

void  j_select__(int* arg0, int* arg1)
{
    japi_select( *arg0, *arg1 );
}

void  j_deselect__(int* arg0, int* arg1)
{
    japi_deselect( *arg0, *arg1 );
}

void  j_multiplemode__(int* arg0, int* arg1)
{
    japi_multiplemode( *arg0, *arg1 );
}

void  j_insert__(int* arg0, int* arg1, char* arg2, int arg3)
{
    char* jstr0 = NULL;
    japi_insert( *arg0, *arg1, __j_f2c( arg2, &jstr0, arg3) );
    free( jstr0 );
}

void  j_remove__(int* arg0, int* arg1)
{
    japi_remove( *arg0, *arg1 );
}

void  j_removeitem__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    japi_removeitem( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
}

void  j_removeall__(int* arg0)
{
    japi_removeall( *arg0 );
}

void  j_setstate__(int* arg0, int* arg1)
{
    japi_setstate( *arg0, *arg1 );
}

void  j_setrows__(int* arg0, int* arg1)
{
    japi_setrows( *arg0, *arg1 );
}

void  j_setcolumns__(int* arg0, int* arg1)
{
    japi_setcolumns( *arg0, *arg1 );
}

void  j_seticon__(int* arg0, int* arg1)
{
    japi_seticon( *arg0, *arg1 );
}

void  j_setimage__(int* arg0, int* arg1)
{
    japi_setimage( *arg0, *arg1 );
}

void  j_setvalue__(int* arg0, int* arg1)
{
    japi_setvalue( *arg0, *arg1 );
}

void  j_setradiogroup__(int* arg0, int* arg1)
{
    japi_setradiogroup( *arg0, *arg1 );
}

void  j_setunitinc__(int* arg0, int* arg1)
{
    japi_setunitinc( *arg0, *arg1 );
}

void  j_setblockinc__(int* arg0, int* arg1)
{
    japi_setblockinc( *arg0, *arg1 );
}

void  j_setmin__(int* arg0, int* arg1)
{
    japi_setmin( *arg0, *arg1 );
}

void  j_setmax__(int* arg0, int* arg1)
{
    japi_setmax( *arg0, *arg1 );
}

void  j_setdanger__(int* arg0, int* arg1)
{
    japi_setdanger( *arg0, *arg1 );
}

void  j_setslidesize__(int* arg0, int* arg1)
{
    japi_setslidesize( *arg0, *arg1 );
}

void  j_setcursor__(int* arg0, int* arg1)
{
    japi_setcursor( *arg0, *arg1 );
}

void  j_setresizable__(int* arg0, int* arg1)
{
    japi_setresizable( *arg0, *arg1 );
}

int   j_getlength__(int* arg0)
{
    int  retval;
    retval = japi_getlength( *arg0 );
    return( retval );
}

int   j_getvalue__(int* arg0)
{
    int  retval;
    retval = japi_getvalue( *arg0 );
    return( retval );
}

int   j_getdanger__(int* arg0)
{
    int  retval;
    retval = japi_getdanger( *arg0 );
    return( retval );
}

int   j_getscreenheight__()
{
    int  retval;
    retval = japi_getscreenheight(  );
    return( retval );
}

int   j_getscreenwidth__()
{
    int  retval;
    retval = japi_getscreenwidth(  );
    return( retval );
}

int   j_getheight__(int* arg0)
{
    int  retval;
    retval = japi_getheight( *arg0 );
    return( retval );
}

int   j_getwidth__(int* arg0)
{
    int  retval;
    retval = japi_getwidth( *arg0 );
    return( retval );
}

int   j_getinsets__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_getinsets( *arg0, *arg1 );
    return( retval );
}

int   j_getlayoutid__(int* arg0)
{
    int  retval;
    retval = japi_getlayoutid( *arg0 );
    return( retval );
}

int   j_getinheight__(int* arg0)
{
    int  retval;
    retval = japi_getinheight( *arg0 );
    return( retval );
}

int   j_getinwidth__(int* arg0)
{
    int  retval;
    retval = japi_getinwidth( *arg0 );
    return( retval );
}

void j_gettext__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    japi_gettext( *arg0, __j_f2c_d( arg1, arg2) );
    __j_c2f(arg1, arg2);
    free( jstr0 );
}

void j_getitem__(int* arg0, int* arg1, char* arg2, int arg3)
{
    char* jstr0 = NULL;
    japi_getitem( *arg0, *arg1, __j_f2c_d( arg2, arg3) );
    __j_c2f(arg2, arg3);
    free( jstr0 );
}

int   j_getitemcount__(int* arg0)
{
    int  retval;
    retval = japi_getitemcount( *arg0 );
    return( retval );
}

void  j_delete__(int* arg0, int* arg1, int* arg2)
{
    japi_delete( *arg0, *arg1, *arg2 );
}

void  j_replacetext__(int* arg0, char* arg1, int* arg2, int* arg3, int arg4)
{
    char* jstr0 = NULL;
    japi_replacetext( *arg0, __j_f2c( arg1, &jstr0, arg4), *arg2, *arg3 );
    free( jstr0 );
}

void  j_appendtext__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    japi_appendtext( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
}

void  j_inserttext__(int* arg0, char* arg1, int* arg2, int arg3)
{
    char* jstr0 = NULL;
    japi_inserttext( *arg0, __j_f2c( arg1, &jstr0, arg3), *arg2 );
    free( jstr0 );
}

void  j_settext__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    japi_settext( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
}

void  j_selectall__(int* arg0)
{
    japi_selectall( *arg0 );
}

void  j_selecttext__(int* arg0, int* arg1, int* arg2)
{
    japi_selecttext( *arg0, *arg1, *arg2 );
}

int   j_getselstart__(int* arg0)
{
    int  retval;
    retval = japi_getselstart( *arg0 );
    return( retval );
}

int   j_getselend__(int* arg0)
{
    int  retval;
    retval = japi_getselend( *arg0 );
    return( retval );
}

void j_getseltext__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    japi_getseltext( *arg0, __j_f2c_d( arg1, arg2) );
    __j_c2f(arg1, arg2);
    free( jstr0 );
}

int   j_getcurpos__(int* arg0)
{
    int  retval;
    retval = japi_getcurpos( *arg0 );
    return( retval );
}

void  j_setcurpos__(int* arg0, int* arg1)
{
    japi_setcurpos( *arg0, *arg1 );
}

void  j_setechochar__(int* arg0, char* arg1)
{
    japi_setechochar( *arg0, *arg1 );
}

void  j_seteditable__(int* arg0, int* arg1)
{
    japi_seteditable( *arg0, *arg1 );
}

void  j_setshortcut__(int* arg0, char* arg1)
{
    japi_setshortcut( *arg0, *arg1 );
}

void  j_quit__()
{
    japi_quit(  );
}

void  j_kill__()
{
    japi_kill(  );
}

void  j_setsize__(int* arg0, int* arg1, int* arg2)
{
    japi_setsize( *arg0, *arg1, *arg2 );
}

int   j_getaction__()
{
    int  retval;
    retval = japi_getaction(  );
    return( retval );
}

int   j_nextaction__()
{
    int  retval;
    retval = japi_nextaction(  );
    return( retval );
}

void  j_show__(int* arg0)
{
    japi_show( *arg0 );
}

void  j_showpopup__(int* arg0, int* arg1, int* arg2)
{
    japi_showpopup( *arg0, *arg1, *arg2 );
}

void  j_add__(int* arg0, int* arg1)
{
    japi_add( *arg0, *arg1 );
}

void  j_release__(int* arg0)
{
    japi_release( *arg0 );
}

void  j_releaseall__(int* arg0)
{
    japi_releaseall( *arg0 );
}

void  j_hide__(int* arg0)
{
    japi_hide( *arg0 );
}

void  j_dispose__(int* arg0)
{
    japi_dispose( *arg0 );
}

void  j_setpos__(int* arg0, int* arg1, int* arg2)
{
    japi_setpos( *arg0, *arg1, *arg2 );
}

int   j_getviewportheight__(int* arg0)
{
    int  retval;
    retval = japi_getviewportheight( *arg0 );
    return( retval );
}

int   j_getviewportwidth__(int* arg0)
{
    int  retval;
    retval = japi_getviewportwidth( *arg0 );
    return( retval );
}

int   j_getxpos__(int* arg0)
{
    int  retval;
    retval = japi_getxpos( *arg0 );
    return( retval );
}

int   j_getypos__(int* arg0)
{
    int  retval;
    retval = japi_getypos( *arg0 );
    return( retval );
}

void  j_getpos__(int* arg0, int* arg1, int* arg2)
{
    japi_getpos( *arg0, arg1, arg2 );
}

int   j_getparentid__(int* arg0)
{
    int  retval;
    retval = japi_getparentid( *arg0 );
    return( retval );
}

void  j_setfocus__(int* arg0)
{
    japi_setfocus( *arg0 );
}

int   j_hasfocus__(int* arg0)
{
    int  retval;
    retval = japi_hasfocus( *arg0 );
    return( retval );
}

int   j_getstringwidth__(int* arg0, char* arg1, int arg2)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_getstringwidth( *arg0, __j_f2c( arg1, &jstr0, arg2) );
    free( jstr0 );
    return( retval );
}

int   j_getfontheight__(int* arg0)
{
    int  retval;
    retval = japi_getfontheight( *arg0 );
    return( retval );
}

int   j_getfontascent__(int* arg0)
{
    int  retval;
    retval = japi_getfontascent( *arg0 );
    return( retval );
}

int   j_keylistener__(int* arg0)
{
    int  retval;
    retval = japi_keylistener( *arg0 );
    return( retval );
}

int   j_getkeycode__(int* arg0)
{
    int  retval;
    retval = japi_getkeycode( *arg0 );
    return( retval );
}

int   j_getkeychar__(int* arg0)
{
    int  retval;
    retval = japi_getkeychar( *arg0 );
    return( retval );
}

int   j_mouselistener__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_mouselistener( *arg0, *arg1 );
    return( retval );
}

int   j_getmousex__(int* arg0)
{
    int  retval;
    retval = japi_getmousex( *arg0 );
    return( retval );
}

int   j_getmousey__(int* arg0)
{
    int  retval;
    retval = japi_getmousey( *arg0 );
    return( retval );
}

void  j_getmousepos__(int* arg0, int* arg1, int* arg2)
{
    japi_getmousepos( *arg0, arg1, arg2 );
}

int   j_getmousebutton__(int* arg0)
{
    int  retval;
    retval = japi_getmousebutton( *arg0 );
    return( retval );
}

int   j_focuslistener__(int* arg0)
{
    int  retval;
    retval = japi_focuslistener( *arg0 );
    return( retval );
}

int   j_componentlistener__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_componentlistener( *arg0, *arg1 );
    return( retval );
}

int   j_windowlistener__(int* arg0, int* arg1)
{
    int  retval;
    retval = japi_windowlistener( *arg0, *arg1 );
    return( retval );
}

void  j_setflowlayout__(int* arg0, int* arg1)
{
    japi_setflowlayout( *arg0, *arg1 );
}

void  j_setborderlayout__(int* arg0)
{
    japi_setborderlayout( *arg0 );
}

void  j_setgridlayout__(int* arg0, int* arg1, int* arg2)
{
    japi_setgridlayout( *arg0, *arg1, *arg2 );
}

void  j_setfixlayout__(int* arg0)
{
    japi_setfixlayout( *arg0 );
}

void  j_setnolayout__(int* arg0)
{
    japi_setnolayout( *arg0 );
}

void  j_setborderpos__(int* arg0, int* arg1)
{
    japi_setborderpos( *arg0, *arg1 );
}

void  j_sethgap__(int* arg0, int* arg1)
{
    japi_sethgap( *arg0, *arg1 );
}

void  j_setvgap__(int* arg0, int* arg1)
{
    japi_setvgap( *arg0, *arg1 );
}

void  j_setinsets__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4)
{
    japi_setinsets( *arg0, *arg1, *arg2, *arg3, *arg4 );
}

void  j_setalign__(int* arg0, int* arg1)
{
    japi_setalign( *arg0, *arg1 );
}

void  j_setflowfill__(int* arg0, int* arg1)
{
    japi_setflowfill( *arg0, *arg1 );
}

void  j_translate__(int* arg0, int* arg1, int* arg2)
{
    japi_translate( *arg0, *arg1, *arg2 );
}

void  j_cliprect__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4)
{
    japi_cliprect( *arg0, *arg1, *arg2, *arg3, *arg4 );
}

void  j_drawrect__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4)
{
    japi_drawrect( *arg0, *arg1, *arg2, *arg3, *arg4 );
}

void  j_fillrect__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4)
{
    japi_fillrect( *arg0, *arg1, *arg2, *arg3, *arg4 );
}

void  j_drawroundrect__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6)
{
    japi_drawroundrect( *arg0, *arg1, *arg2, *arg3, *arg4, *arg5, *arg6 );
}

void  j_fillroundrect__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6)
{
    japi_fillroundrect( *arg0, *arg1, *arg2, *arg3, *arg4, *arg5, *arg6 );
}

void  j_drawoval__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4)
{
    japi_drawoval( *arg0, *arg1, *arg2, *arg3, *arg4 );
}

void  j_filloval__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4)
{
    japi_filloval( *arg0, *arg1, *arg2, *arg3, *arg4 );
}

void  j_drawcircle__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_drawcircle( *arg0, *arg1, *arg2, *arg3 );
}

void  j_fillcircle__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_fillcircle( *arg0, *arg1, *arg2, *arg3 );
}

void  j_drawarc__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6)
{
    japi_drawarc( *arg0, *arg1, *arg2, *arg3, *arg4, *arg5, *arg6 );
}

void  j_fillarc__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6)
{
    japi_fillarc( *arg0, *arg1, *arg2, *arg3, *arg4, *arg5, *arg6 );
}

void  j_drawline__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4)
{
    japi_drawline( *arg0, *arg1, *arg2, *arg3, *arg4 );
}

void  j_drawpolyline__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_drawpolyline( *arg0, *arg1, arg2, arg3 );
}

void  j_drawpolygon__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_drawpolygon( *arg0, *arg1, arg2, arg3 );
}

void  j_fillpolygon__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_fillpolygon( *arg0, *arg1, arg2, arg3 );
}

void  j_drawpixel__(int* arg0, int* arg1, int* arg2)
{
    japi_drawpixel( *arg0, *arg1, *arg2 );
}

void  j_drawstring__(int* arg0, int* arg1, int* arg2, char* arg3, int arg4)
{
    char* jstr0 = NULL;
    japi_drawstring( *arg0, *arg1, *arg2, __j_f2c( arg3, &jstr0, arg4) );
    free( jstr0 );
}

void  j_setxor__(int* arg0, int* arg1)
{
    japi_setxor( *arg0, *arg1 );
}

int   j_getimage__(int* arg0)
{
    int  retval;
    retval = japi_getimage( *arg0 );
    return( retval );
}

void  j_getimagesource__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6, int* arg7)
{
    japi_getimagesource( *arg0, *arg1, *arg2, *arg3, *arg4, arg5, arg6, arg7 );
}

void  j_drawimagesource__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6, int* arg7)
{
    japi_drawimagesource( *arg0, *arg1, *arg2, *arg3, *arg4, arg5, arg6, arg7 );
}

int   j_getscaledimage__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6)
{
    int  retval;
    retval = japi_getscaledimage( *arg0, *arg1, *arg2, *arg3, *arg4, *arg5, *arg6 );
    return( retval );
}

void  j_drawimage__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_drawimage( *arg0, *arg1, *arg2, *arg3 );
}

void  j_drawscaledimage__(int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6, int* arg7, int* arg8, int* arg9)
{
    japi_drawscaledimage( *arg0, *arg1, *arg2, *arg3, *arg4, *arg5, *arg6, *arg7, *arg8, *arg9 );
}

void  j_setcolor__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_setcolor( *arg0, *arg1, *arg2, *arg3 );
}

void  j_setcolorbg__(int* arg0, int* arg1, int* arg2, int* arg3)
{
    japi_setcolorbg( *arg0, *arg1, *arg2, *arg3 );
}

void  j_setnamedcolor__(int* arg0, int* arg1)
{
    japi_setnamedcolor( *arg0, *arg1 );
}

void  j_setnamedcolorbg__(int* arg0, int* arg1)
{
    japi_setnamedcolorbg( *arg0, *arg1 );
}

int   j_loadimage__(char* arg0, int arg1)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_loadimage( __j_f2c( arg0, &jstr0, arg1) );
    free( jstr0 );
    return( retval );
}

int   j_saveimage__(int* arg0, char* arg1, int* arg2, int arg3)
{
    char* jstr0 = NULL;
    int  retval;
    retval = japi_saveimage( *arg0, __j_f2c( arg1, &jstr0, arg3), *arg2 );
    free( jstr0 );
    return( retval );
}

void  j_sync__()
{
    japi_sync(  );
}

void  j_beep__()
{
    japi_beep(  );
}

int   j_random__()
{
    int  retval;
    retval = japi_random(  );
    return( retval );
}

void  j_sleep__(int* arg0)
{
    japi_sleep( *arg0 );
}




/* Once again with ONE underscore (F90) */

int   j_start_ (  )
{    return(j_start__( ));  }

int   j_connect_ ( char* arg0, int arg1  )
{    return(j_connect__(  arg0 , arg1 ));  }

void  j_setport_ ( int* arg0 )
{    j_setport__(  arg0 );  }

void  j_setdebug_ ( int* arg0 )
{    j_setdebug__(  arg0 );  }

int   j_frame_ ( char* arg0, int arg1  )
{    return(j_frame__(  arg0 , arg1 ));  }

int   j_button_ ( int* arg0, char* arg1, int arg2  )
{    return(j_button__(  arg0 , arg1 , arg2 ));  }

int   j_graphicbutton_ ( int* arg0, char* arg1, int arg2  )
{    return(j_graphicbutton__(  arg0 , arg1 , arg2 ));  }

int   j_checkbox_ ( int* arg0, char* arg1, int arg2  )
{    return(j_checkbox__(  arg0 , arg1 , arg2 ));  }

int   j_label_ ( int* arg0, char* arg1, int arg2  )
{    return(j_label__(  arg0 , arg1 , arg2 ));  }

int   j_graphiclabel_ ( int* arg0, char* arg1, int arg2  )
{    return(j_graphiclabel__(  arg0 , arg1 , arg2 ));  }

int   j_canvas_ ( int* arg0, int* arg1, int* arg2 )
{    return(j_canvas__(  arg0 , arg1 , arg2 ));  }

int   j_panel_ ( int* arg0 )
{    return(j_panel__(  arg0 ));  }

int   j_borderpanel_ ( int* arg0, int* arg1 )
{    return(j_borderpanel__(  arg0 , arg1 ));  }

int   j_radiogroup_ ( int* arg0 )
{    return(j_radiogroup__(  arg0 ));  }

int   j_radiobutton_ ( int* arg0, char* arg1, int arg2  )
{    return(j_radiobutton__(  arg0 , arg1 , arg2 ));  }

int   j_list_ ( int* arg0, int* arg1 )
{    return(j_list__(  arg0 , arg1 ));  }

int   j_choice_ ( int* arg0 )
{    return(j_choice__(  arg0 ));  }

int   j_dialog_ ( int* arg0, char* arg1, int arg2  )
{    return(j_dialog__(  arg0 , arg1 , arg2 ));  }

int   j_window_ ( int* arg0 )
{    return(j_window__(  arg0 ));  }

int   j_popupmenu_ ( int* arg0, char* arg1, int arg2  )
{    return(j_popupmenu__(  arg0 , arg1 , arg2 ));  }

int   j_scrollpane_ ( int* arg0 )
{    return(j_scrollpane__(  arg0 ));  }

int   j_hscrollbar_ ( int* arg0 )
{    return(j_hscrollbar__(  arg0 ));  }

int   j_vscrollbar_ ( int* arg0 )
{    return(j_vscrollbar__(  arg0 ));  }

int   j_line_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    return(j_line__(  arg0 , arg1 , arg2 , arg3 ));  }

int   j_printer_ ( int* arg0 )
{    return(j_printer__(  arg0 ));  }

int   j_image_ ( int* arg0, int* arg1 )
{    return(j_image__(  arg0 , arg1 ));  }

void j_filedialog_ ( int* arg0, char* arg1, char* arg2, char* arg3, int arg4 , int arg5 , int arg6  )
{    j_filedialog__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 );  }

void j_fileselect_ ( int* arg0, char* arg1, char* arg2, char* arg3, int arg4 , int arg5 , int arg6  )
{    j_fileselect__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 );  }

int   j_messagebox_ ( int* arg0, char* arg1, char* arg2, int arg3 , int arg4  )
{    return(j_messagebox__(  arg0 , arg1 , arg2 , arg3 , arg4 ));  }

int   j_alertbox_ ( int* arg0, char* arg1, char* arg2, char* arg3, int arg4 , int arg5 , int arg6  )
{    return(j_alertbox__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 ));  }

int   j_choicebox2_ ( int* arg0, char* arg1, char* arg2, char* arg3, char* arg4, int arg5 , int arg6 , int arg7 , int arg8  )
{    return(j_choicebox2__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 , arg7 , arg8 ));  }

int   j_choicebox3_ ( int* arg0, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, int arg6 , int arg7 , int arg8 , int arg9 , int arg10  )
{    return(j_choicebox3__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 , arg7 , arg8 , arg9 , arg10 ));  }

int   j_progressbar_ ( int* arg0, int* arg1 )
{    return(j_progressbar__(  arg0 , arg1 ));  }

int   j_led_ ( int* arg0, int* arg1, int* arg2 )
{    return(j_led__(  arg0 , arg1 , arg2 ));  }

int   j_sevensegment_ ( int* arg0, int* arg1 )
{    return(j_sevensegment__(  arg0 , arg1 ));  }

int   j_meter_ ( int* arg0, char* arg1, int arg2  )
{    return(j_meter__(  arg0 , arg1 , arg2 ));  }

void  j_additem_ ( int* arg0, char* arg1, int arg2  )
{    j_additem__(  arg0 , arg1 , arg2 );  }

int   j_textfield_ ( int* arg0, int* arg1 )
{    return(j_textfield__(  arg0 , arg1 ));  }

int   j_textarea_ ( int* arg0, int* arg1, int* arg2 )
{    return(j_textarea__(  arg0 , arg1 , arg2 ));  }

int   j_menubar_ ( int* arg0 )
{    return(j_menubar__(  arg0 ));  }

int   j_menu_ ( int* arg0, char* arg1, int arg2  )
{    return(j_menu__(  arg0 , arg1 , arg2 ));  }

int   j_helpmenu_ ( int* arg0, char* arg1, int arg2  )
{    return(j_helpmenu__(  arg0 , arg1 , arg2 ));  }

int   j_menuitem_ ( int* arg0, char* arg1, int arg2  )
{    return(j_menuitem__(  arg0 , arg1 , arg2 ));  }

int   j_checkmenuitem_ ( int* arg0, char* arg1, int arg2  )
{    return(j_checkmenuitem__(  arg0 , arg1 , arg2 ));  }

void  j_pack_ ( int* arg0 )
{    j_pack__(  arg0 );  }

void  j_print_ ( int* arg0 )
{    j_print__(  arg0 );  }

void  j_playsoundfile_ ( char* arg0, int arg1  )
{    j_playsoundfile__(  arg0 , arg1 );  }

void  j_play_ ( int* arg0 )
{    j_play__(  arg0 );  }

int   j_sound_ ( char* arg0, int arg1  )
{    return(j_sound__(  arg0 , arg1 ));  }

void  j_setfont_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_setfont__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_setfontname_ ( int* arg0, int* arg1 )
{    j_setfontname__(  arg0 , arg1 );  }

void  j_setfontsize_ ( int* arg0, int* arg1 )
{    j_setfontsize__(  arg0 , arg1 );  }

void  j_setfontstyle_ ( int* arg0, int* arg1 )
{    j_setfontstyle__(  arg0 , arg1 );  }

void  j_seperator_ ( int* arg0 )
{    j_seperator__(  arg0 );  }

void  j_disable_ ( int* arg0 )
{    j_disable__(  arg0 );  }

void  j_enable_ ( int* arg0 )
{    j_enable__(  arg0 );  }

int   j_getstate_ ( int* arg0 )
{    return(j_getstate__(  arg0 ));  }

int   j_getrows_ ( int* arg0 )
{    return(j_getrows__(  arg0 ));  }

int   j_getcolumns_ ( int* arg0 )
{    return(j_getcolumns__(  arg0 ));  }

int   j_getselect_ ( int* arg0 )
{    return(j_getselect__(  arg0 ));  }

int   j_isselect_ ( int* arg0, int* arg1 )
{    return(j_isselect__(  arg0 , arg1 ));  }

int   j_isvisible_ ( int* arg0 )
{    return(j_isvisible__(  arg0 ));  }

int   j_isparent_ ( int* arg0, int* arg1 )
{    return(j_isparent__(  arg0 , arg1 ));  }

int   j_isresizable_ ( int* arg0 )
{    return(j_isresizable__(  arg0 ));  }

void  j_select_ ( int* arg0, int* arg1 )
{    j_select__(  arg0 , arg1 );  }

void  j_deselect_ ( int* arg0, int* arg1 )
{    j_deselect__(  arg0 , arg1 );  }

void  j_multiplemode_ ( int* arg0, int* arg1 )
{    j_multiplemode__(  arg0 , arg1 );  }

void  j_insert_ ( int* arg0, int* arg1, char* arg2, int arg3  )
{    j_insert__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_remove_ ( int* arg0, int* arg1 )
{    j_remove__(  arg0 , arg1 );  }

void  j_removeitem_ ( int* arg0, char* arg1, int arg2  )
{    j_removeitem__(  arg0 , arg1 , arg2 );  }

void  j_removeall_ ( int* arg0 )
{    j_removeall__(  arg0 );  }

void  j_setstate_ ( int* arg0, int* arg1 )
{    j_setstate__(  arg0 , arg1 );  }

void  j_setrows_ ( int* arg0, int* arg1 )
{    j_setrows__(  arg0 , arg1 );  }

void  j_setcolumns_ ( int* arg0, int* arg1 )
{    j_setcolumns__(  arg0 , arg1 );  }

void  j_seticon_ ( int* arg0, int* arg1 )
{    j_seticon__(  arg0 , arg1 );  }

void  j_setimage_ ( int* arg0, int* arg1 )
{    j_setimage__(  arg0 , arg1 );  }

void  j_setvalue_ ( int* arg0, int* arg1 )
{    j_setvalue__(  arg0 , arg1 );  }

void  j_setradiogroup_ ( int* arg0, int* arg1 )
{    j_setradiogroup__(  arg0 , arg1 );  }

void  j_setunitinc_ ( int* arg0, int* arg1 )
{    j_setunitinc__(  arg0 , arg1 );  }

void  j_setblockinc_ ( int* arg0, int* arg1 )
{    j_setblockinc__(  arg0 , arg1 );  }

void  j_setmin_ ( int* arg0, int* arg1 )
{    j_setmin__(  arg0 , arg1 );  }

void  j_setmax_ ( int* arg0, int* arg1 )
{    j_setmax__(  arg0 , arg1 );  }

void  j_setdanger_ ( int* arg0, int* arg1 )
{    j_setdanger__(  arg0 , arg1 );  }

void  j_setslidesize_ ( int* arg0, int* arg1 )
{    j_setslidesize__(  arg0 , arg1 );  }

void  j_setcursor_ ( int* arg0, int* arg1 )
{    j_setcursor__(  arg0 , arg1 );  }

void  j_setresizable_ ( int* arg0, int* arg1 )
{    j_setresizable__(  arg0 , arg1 );  }

int   j_getlength_ ( int* arg0 )
{    return(j_getlength__(  arg0 ));  }

int   j_getvalue_ ( int* arg0 )
{    return(j_getvalue__(  arg0 ));  }

int   j_getdanger_ ( int* arg0 )
{    return(j_getdanger__(  arg0 ));  }

int   j_getscreenheight_ (  )
{    return(j_getscreenheight__( ));  }

int   j_getscreenwidth_ (  )
{    return(j_getscreenwidth__( ));  }

int   j_getheight_ ( int* arg0 )
{    return(j_getheight__(  arg0 ));  }

int   j_getwidth_ ( int* arg0 )
{    return(j_getwidth__(  arg0 ));  }

int   j_getinsets_ ( int* arg0, int* arg1 )
{    return(j_getinsets__(  arg0 , arg1 ));  }

int   j_getlayoutid_ ( int* arg0 )
{    return(j_getlayoutid__(  arg0 ));  }

int   j_getinheight_ ( int* arg0 )
{    return(j_getinheight__(  arg0 ));  }

int   j_getinwidth_ ( int* arg0 )
{    return(j_getinwidth__(  arg0 ));  }

void j_gettext_ ( int* arg0, char* arg1, int arg2  )
{    j_gettext__(  arg0 , arg1 , arg2 );  }

void j_getitem_ ( int* arg0, int* arg1, char* arg2, int arg3  )
{    j_getitem__(  arg0 , arg1 , arg2 , arg3 );  }

int   j_getitemcount_ ( int* arg0 )
{    return(j_getitemcount__(  arg0 ));  }

void  j_delete_ ( int* arg0, int* arg1, int* arg2 )
{    j_delete__(  arg0 , arg1 , arg2 );  }

void  j_replacetext_ ( int* arg0, char* arg1, int* arg2, int* arg3, int arg4  )
{    j_replacetext__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_appendtext_ ( int* arg0, char* arg1, int arg2  )
{    j_appendtext__(  arg0 , arg1 , arg2 );  }

void  j_inserttext_ ( int* arg0, char* arg1, int* arg2, int arg3  )
{    j_inserttext__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_settext_ ( int* arg0, char* arg1, int arg2  )
{    j_settext__(  arg0 , arg1 , arg2 );  }

void  j_selectall_ ( int* arg0 )
{    j_selectall__(  arg0 );  }

void  j_selecttext_ ( int* arg0, int* arg1, int* arg2 )
{    j_selecttext__(  arg0 , arg1 , arg2 );  }

int   j_getselstart_ ( int* arg0 )
{    return(j_getselstart__(  arg0 ));  }

int   j_getselend_ ( int* arg0 )
{    return(j_getselend__(  arg0 ));  }

void j_getseltext_ ( int* arg0, char* arg1, int arg2  )
{    j_getseltext__(  arg0 , arg1 , arg2 );  }

int   j_getcurpos_ ( int* arg0 )
{    return(j_getcurpos__(  arg0 ));  }

void  j_setcurpos_ ( int* arg0, int* arg1 )
{    j_setcurpos__(  arg0 , arg1 );  }

void  j_setechochar_ ( int* arg0, char* arg1 )
{    j_setechochar__(  arg0 , arg1 );  }

void  j_seteditable_ ( int* arg0, int* arg1 )
{    j_seteditable__(  arg0 , arg1 );  }

void  j_setshortcut_ ( int* arg0, char* arg1 )
{    j_setshortcut__(  arg0 , arg1 );  }

void  j_quit_ (  )
{    j_quit__( );  }

void  j_kill_ (  )
{    j_kill__( );  }

void  j_setsize_ ( int* arg0, int* arg1, int* arg2 )
{    j_setsize__(  arg0 , arg1 , arg2 );  }

int   j_getaction_ (  )
{    return(j_getaction__( ));  }

int   j_nextaction_ (  )
{    return(j_nextaction__( ));  }

void  j_show_ ( int* arg0 )
{    j_show__(  arg0 );  }

void  j_showpopup_ ( int* arg0, int* arg1, int* arg2 )
{    j_showpopup__(  arg0 , arg1 , arg2 );  }

void  j_add_ ( int* arg0, int* arg1 )
{    j_add__(  arg0 , arg1 );  }

void  j_release_ ( int* arg0 )
{    j_release__(  arg0 );  }

void  j_releaseall_ ( int* arg0 )
{    j_releaseall__(  arg0 );  }

void  j_hide_ ( int* arg0 )
{    j_hide__(  arg0 );  }

void  j_dispose_ ( int* arg0 )
{    j_dispose__(  arg0 );  }

void  j_setpos_ ( int* arg0, int* arg1, int* arg2 )
{    j_setpos__(  arg0 , arg1 , arg2 );  }

int   j_getviewportheight_ ( int* arg0 )
{    return(j_getviewportheight__(  arg0 ));  }

int   j_getviewportwidth_ ( int* arg0 )
{    return(j_getviewportwidth__(  arg0 ));  }

int   j_getxpos_ ( int* arg0 )
{    return(j_getxpos__(  arg0 ));  }

int   j_getypos_ ( int* arg0 )
{    return(j_getypos__(  arg0 ));  }

void  j_getpos_ ( int* arg0, int* arg1, int* arg2 )
{    j_getpos__(  arg0 , arg1 , arg2 );  }

int   j_getparentid_ ( int* arg0 )
{    return(j_getparentid__(  arg0 ));  }

void  j_setfocus_ ( int* arg0 )
{    j_setfocus__(  arg0 );  }

int   j_hasfocus_ ( int* arg0 )
{    return(j_hasfocus__(  arg0 ));  }

int   j_getstringwidth_ ( int* arg0, char* arg1, int arg2  )
{    return(j_getstringwidth__(  arg0 , arg1 , arg2 ));  }

int   j_getfontheight_ ( int* arg0 )
{    return(j_getfontheight__(  arg0 ));  }

int   j_getfontascent_ ( int* arg0 )
{    return(j_getfontascent__(  arg0 ));  }

int   j_keylistener_ ( int* arg0 )
{    return(j_keylistener__(  arg0 ));  }

int   j_getkeycode_ ( int* arg0 )
{    return(j_getkeycode__(  arg0 ));  }

int   j_getkeychar_ ( int* arg0 )
{    return(j_getkeychar__(  arg0 ));  }

int   j_mouselistener_ ( int* arg0, int* arg1 )
{    return(j_mouselistener__(  arg0 , arg1 ));  }

int   j_getmousex_ ( int* arg0 )
{    return(j_getmousex__(  arg0 ));  }

int   j_getmousey_ ( int* arg0 )
{    return(j_getmousey__(  arg0 ));  }

void  j_getmousepos_ ( int* arg0, int* arg1, int* arg2 )
{    j_getmousepos__(  arg0 , arg1 , arg2 );  }

int   j_getmousebutton_ ( int* arg0 )
{    return(j_getmousebutton__(  arg0 ));  }

int   j_focuslistener_ ( int* arg0 )
{    return(j_focuslistener__(  arg0 ));  }

int   j_componentlistener_ ( int* arg0, int* arg1 )
{    return(j_componentlistener__(  arg0 , arg1 ));  }

int   j_windowlistener_ ( int* arg0, int* arg1 )
{    return(j_windowlistener__(  arg0 , arg1 ));  }

void  j_setflowlayout_ ( int* arg0, int* arg1 )
{    j_setflowlayout__(  arg0 , arg1 );  }

void  j_setborderlayout_ ( int* arg0 )
{    j_setborderlayout__(  arg0 );  }

void  j_setgridlayout_ ( int* arg0, int* arg1, int* arg2 )
{    j_setgridlayout__(  arg0 , arg1 , arg2 );  }

void  j_setfixlayout_ ( int* arg0 )
{    j_setfixlayout__(  arg0 );  }

void  j_setnolayout_ ( int* arg0 )
{    j_setnolayout__(  arg0 );  }

void  j_setborderpos_ ( int* arg0, int* arg1 )
{    j_setborderpos__(  arg0 , arg1 );  }

void  j_sethgap_ ( int* arg0, int* arg1 )
{    j_sethgap__(  arg0 , arg1 );  }

void  j_setvgap_ ( int* arg0, int* arg1 )
{    j_setvgap__(  arg0 , arg1 );  }

void  j_setinsets_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4 )
{    j_setinsets__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_setalign_ ( int* arg0, int* arg1 )
{    j_setalign__(  arg0 , arg1 );  }

void  j_setflowfill_ ( int* arg0, int* arg1 )
{    j_setflowfill__(  arg0 , arg1 );  }

void  j_translate_ ( int* arg0, int* arg1, int* arg2 )
{    j_translate__(  arg0 , arg1 , arg2 );  }

void  j_cliprect_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4 )
{    j_cliprect__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_drawrect_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4 )
{    j_drawrect__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_fillrect_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4 )
{    j_fillrect__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_drawroundrect_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6 )
{    j_drawroundrect__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 );  }

void  j_fillroundrect_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6 )
{    j_fillroundrect__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 );  }

void  j_drawoval_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4 )
{    j_drawoval__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_filloval_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4 )
{    j_filloval__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_drawcircle_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_drawcircle__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_fillcircle_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_fillcircle__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_drawarc_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6 )
{    j_drawarc__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 );  }

void  j_fillarc_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6 )
{    j_fillarc__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 );  }

void  j_drawline_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4 )
{    j_drawline__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_drawpolyline_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_drawpolyline__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_drawpolygon_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_drawpolygon__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_fillpolygon_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_fillpolygon__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_drawpixel_ ( int* arg0, int* arg1, int* arg2 )
{    j_drawpixel__(  arg0 , arg1 , arg2 );  }

void  j_drawstring_ ( int* arg0, int* arg1, int* arg2, char* arg3, int arg4  )
{    j_drawstring__(  arg0 , arg1 , arg2 , arg3 , arg4 );  }

void  j_setxor_ ( int* arg0, int* arg1 )
{    j_setxor__(  arg0 , arg1 );  }

int   j_getimage_ ( int* arg0 )
{    return(j_getimage__(  arg0 ));  }

void  j_getimagesource_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6, int* arg7 )
{    j_getimagesource__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 , arg7 );  }

void  j_drawimagesource_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6, int* arg7 )
{    j_drawimagesource__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 , arg7 );  }

int   j_getscaledimage_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6 )
{    return(j_getscaledimage__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 ));  }

void  j_drawimage_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_drawimage__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_drawscaledimage_ ( int* arg0, int* arg1, int* arg2, int* arg3, int* arg4, int* arg5, int* arg6, int* arg7, int* arg8, int* arg9 )
{    j_drawscaledimage__(  arg0 , arg1 , arg2 , arg3 , arg4 , arg5 , arg6 , arg7 , arg8 , arg9 );  }

void  j_setcolor_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_setcolor__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_setcolorbg_ ( int* arg0, int* arg1, int* arg2, int* arg3 )
{    j_setcolorbg__(  arg0 , arg1 , arg2 , arg3 );  }

void  j_setnamedcolor_ ( int* arg0, int* arg1 )
{    j_setnamedcolor__(  arg0 , arg1 );  }

void  j_setnamedcolorbg_ ( int* arg0, int* arg1 )
{    j_setnamedcolorbg__(  arg0 , arg1 );  }

int   j_loadimage_ ( char* arg0, int arg1  )
{    return(j_loadimage__(  arg0 , arg1 ));  }

int   j_saveimage_ ( int* arg0, char* arg1, int* arg2, int arg3  )
{    return(j_saveimage__(  arg0 , arg1 , arg2 , arg3 ));  }

void  j_sync_ (  )
{    j_sync__( );  }

void  j_beep_ (  )
{    j_beep__( );  }

int   j_random_ (  )
{    return(j_random__( ));  }

void  j_sleep_ ( int* arg0 )
{    j_sleep__(  arg0 );  }




